#Saving data
artifacts_root : artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion #creating the folder
  source_URL: 'https://drive.google.com/file/d/1aaGAUQP6O8P843ESU3UXaFwsJ4PLJs_Z/view?usp=sharing' #Download from this URl
  local_data_file: artifacts/data_ingestion/data.zip #Save the downloaded data as data.zip file
  unzip_dir: artifacts/data_ingestion  #unzip the file

prepare_base_model:
  root_dir: artifacts/prepare_base_model #creating the folder
  base_model_path: artifacts/prepare_base_model/base_model.h5 #Download from this URl
  updated_base_model_path: artifacts/prepare_base_model/base_model_updated.h5 #Save the downloaded data 

training:
  root_dir: artifacts/training #creating the folder
  trained_model_path: artifacts/training/model.h5 #Download from this URl

